#!/bin/bash
#primo.bash

n=$1

if [ $n -gt 1 ]
then
	condicao=false
	for ((i=2; i<=n-1; i++))
	do
		if [ $(($n % i)) -eq 0 ]
		then
			condicao=true
			break
		fi
	done
	if $condicao
	then 
		echo "Não é PRIMO"
	else
		echo "É PRIMO"
	fi
fi
