#!/bin/bash
#calculaPrimo.bash
n=2

while true
do
        condicao=false
        for ((i=2; i<=n-1; i++))
        do
                if [ $(($n % $i)) -eq 0 ]
                then
                        condicao=true
			break
                fi
        done

	if [ $condicao = false ]
	then
		echo $n
	fi

let n++
done
